config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save # => true or false
    # redirect to the show page for the restaurant we just created
    redirect_to article_path(@article), status: :see_other
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path, status: :see_other
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= link_to "Back to articles", article_path %>
<h1 class="text-bold">Edit article</h1>
<%= form_with(model: @article) do |form| %>
  <%= form.label :title %><br/>
  <%= form.text_field :title %><br/>

  <%= form.label :content %><br/>
  <%= form.text_field :content %><br/>

  <%= form.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="articles-container">
  <ul class="articles-list">
    <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article_path(article)%>
      </li>
     <% end %>
  </ul>
</div>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1> Create Article </h1>
<%= link_to 'Back to articles', articles_path %>

<%= render 'form', article: @article %>
<%= form_with(model: @article) do |form| %>
  <%= form.label :title %><br/>
  <%= form.text_field :title %><br/>

  <%= form.label :content %><br/>
  <%= form.text_field :content %><br/>

  <%= form.submit %>
<% end %>

app/views/articles/show.html.erb
<%= link_to "Back to articles", articles_path %>
<h1> <%= @article.title %></h1>
<p> <%= @article.content %></p>
<%= link_to "Edit article", edit_article_path %>
    <%= link_to "Delete",
  article_path(@article),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>